{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.prometheusRules.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: {{ include "app.fullname" . }}
    interval: {{ .Values.prometheusRules.interval | default "30s" }}
    rules:
    {{- toYaml .Values.prometheusRules.rules | nindent 4 }}
{{- end }}
